# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created

# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path


name: pre-merge-check
on:
  push:
    branches-ignore:
      - master
    paths:
      - '/src/**'
      - 'pom.xml'
      - '.github/**'

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: setup-maven-settings
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          repositories: '[{ "id": "github", "name": "GitHub ey-advisory-technology-testing Apache Maven Packages", "url": "https://maven.pkg.github.com/ey-advisory-technology-testing/*", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.ACCESS_TOKEN }}"}]'

      - name: Checkout Branch
        uses: actions/checkout@v2.3.2

      - name: Set up JDK 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14.0.2
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload jar files and artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestmanaJ
          path: |
            README.md
            target/*.jar